import { StyleSheet } from 'react-native';
import { COLORS } from '@shared/constants/colors.constants';
import { moderateScale, RADIUS, SPACING } from '@shared/constants/styles.constants';
import type { ITheme } from '@shared/types/theme.types';

export const styling = (theme: ITheme) => StyleSheet.create({
  screen: { flex: 1 },
  header: {
    minHeight: moderateScale(62),
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    paddingHorizontal: SPACING.MD,
  },
  backButton: { width: 38, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { flex: 1, fontSize: 17 },
  cartButton: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS[theme].border,
    borderRadius: RADIUS.SM,
    backgroundColor: COLORS[theme].surface,
  },
  cartBadge: {
    position: 'absolute',
    right: -4,
    top: -4,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADIUS.FULL,
    backgroundColor: COLORS[theme]['brand-primary'],
  },
  badgeText: { color: '#FFFFFF', fontSize: 10 },
  searchField: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginHorizontal: SPACING.MD,
    paddingHorizontal: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS[theme]['brand-primary'],
    borderRadius: RADIUS.SM,
    backgroundColor: COLORS[theme].surface,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: SPACING.SM,
    color: COLORS[theme]['text-primary'],
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
  },
  clearButton: { width: 30, height: 36, alignItems: 'center', justifyContent: 'center' },
  categories: { paddingHorizontal: SPACING.MD, paddingVertical: SPACING.MD, gap: SPACING.SM },
  categoryChip: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    borderRadius: RADIUS.FULL,
    borderWidth: 1,
    borderColor: COLORS[theme].border,
    backgroundColor: COLORS[theme].surface,
  },
  categoryChipSelected: { borderColor: COLORS[theme]['brand-primary'], backgroundColor: COLORS[theme]['brand-primary'] },
  categoryLabel: { color: COLORS[theme]['text-secondary'] },
  categoryLabelSelected: { color: '#FFFFFF' },
  results: { paddingHorizontal: SPACING.MD, paddingBottom: SPACING['2XL'], gap: SPACING.SM },
  resultsHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: SPACING.XS },
  resultCount: { marginTop: SPACING.XS, color: COLORS[theme]['text-secondary'] },
  activeFilter: { color: COLORS[theme]['brand-primary'] },
  resultCard: {
    minHeight: 112,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    padding: SPACING.SM,
    borderWidth: 1,
    borderColor: COLORS[theme].border,
    borderRadius: RADIUS.MD,
    backgroundColor: COLORS[theme].surface,
  },
  itemImage: { width: 82, height: 92, borderRadius: RADIUS.SM, backgroundColor: COLORS[theme]['surface-alt'] },
  itemDetails: { flex: 1, minWidth: 0, gap: SPACING.XS },
  secondary: { color: COLORS[theme]['text-secondary'] },
  itemFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACING.XS, marginTop: SPACING.XS },
  addButton: {
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: SPACING.SM,
    borderRadius: RADIUS.XS,
    borderWidth: 1,
    borderColor: COLORS[theme]['brand-primary'],
  },
  addLabel: { color: COLORS[theme]['brand-primary'] },
  emptyState: { minHeight: 260, alignItems: 'center', justifyContent: 'center', gap: SPACING.SM },
  emptyIcon: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.XS,
    borderRadius: RADIUS.FULL,
    backgroundColor: COLORS[theme]['surface-alt'],
  },
  emptyCopy: { color: COLORS[theme]['text-secondary'], textAlign: 'center' },
  resetButton: { padding: SPACING.SM, marginTop: SPACING.XS },
  resetLabel: { color: COLORS[theme]['brand-primary'] },
});