import { StyleSheet } from 'react-native';
import { COLORS } from '@shared/constants/colors.constants';
import { RADIUS, SPACING } from '@shared/constants/styles.constants';
import type { ITheme } from '@shared/types/theme.types';

export const styling = (theme: ITheme) => StyleSheet.create({
    screen: { flex: 1 },
    header: {
      minHeight: 66,
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.SM,
      paddingHorizontal: SPACING.MD,
      borderBottomWidth: 1,
      borderBottomColor: COLORS[theme].border,
    },
    backButton: {
      width: 38,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerCopy: { flex: 1, gap: 2 },
    content: {
      padding: SPACING.MD,
      paddingBottom: SPACING['2XL'],
      gap: SPACING.LG,
    },
    statusCard: {
      gap: SPACING.MD,
      padding: SPACING.MD,
      borderRadius: RADIUS.MD,
      backgroundColor: COLORS[theme].surface,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
    },
    statusHeading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.SM,
    },
    statusIcon: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: RADIUS.SM,
      backgroundColor: COLORS[theme]['brand-primary-soft'],
    },
    statusCopy: { flex: 1, gap: 3 },
    muted: { color: COLORS[theme]['text-secondary'] },
    timeline: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingTop: SPACING.XS,
    },
    timelineStep: { flex: 1, alignItems: 'center', gap: SPACING.XS },
    timelineMark: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 11,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
      backgroundColor: COLORS[theme].surface,
    },
    timelineMarkComplete: {
      borderColor: COLORS[theme]['brand-primary'],
      backgroundColor: COLORS[theme]['brand-primary'],
    },
    timelineLabel: {
      color: COLORS[theme]['text-muted'],
      fontSize: 10,
      textAlign: 'center',
    },
    timelineLabelComplete: { color: COLORS[theme]['text-primary'] },
    timelineLine: {
      position: 'absolute',
      top: 11,
      left: '62%',
      right: '-38%',
      height: 1,
      backgroundColor: COLORS[theme].border,
      zIndex: -1,
    },
    timelineLineComplete: { backgroundColor: COLORS[theme]['brand-primary'] },
    section: { gap: SPACING.SM },
    itemRow: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.SM,
      paddingHorizontal: SPACING.SM,
      borderBottomWidth: 1,
      borderBottomColor: COLORS[theme].border,
    },
    itemQuantity: { minWidth: 30, alignItems: 'center' },
    quantityText: { color: COLORS[theme]['text-secondary'] },
    itemName: { flex: 1 },
    infoCard: {
      gap: SPACING.MD,
      padding: SPACING.MD,
      borderRadius: RADIUS.MD,
      backgroundColor: COLORS[theme].surface,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
    },
    detailRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.SM },
    detailText: { flex: 1, color: COLORS[theme]['text-primary'] },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    totalRow: {
      paddingTop: SPACING.SM,
      borderTopWidth: 1,
      borderTopColor: COLORS[theme].border,
    },
    paymentLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.XS,
    },
    demoNote: { flexDirection: 'row', alignItems: 'center', gap: SPACING.XS },
    notFound: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: SPACING.LG,
      gap: SPACING.MD,
    },
    backLink: { padding: SPACING.SM },
    linkText: { color: COLORS[theme]['brand-primary'] },
  });
