import type { DiningEvent } from '../types/event.types';

export const DINING_EVENTS: DiningEvent[] = [
  {
    id: 'coastal-supper',
    title: 'A Coastal Supper Club',
    category: 'Supper club',
    host: 'Chef Mira Sen',
    dateLabel: 'Sat, Oct 17',
    timeLabel: '7:00 PM',
    venue: 'The Glasshouse',
    neighborhood: 'Koramangala, Bengaluru',
    duration: '2.5 hours',
    price: 1850,
    capacity: 18,
    summary: 'A six-course menu inspired by the western coast.',
    description: 'Settle in for a seasonal menu of coastal ingredients, thoughtful pairings, and stories from Chef Mira’s travels along the Konkan coast.',
    sessions: ['7:00 PM', '7:30 PM'],
    includes: ['Six-course tasting menu', 'Welcome drink', 'Vegetarian menu available'],
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=85',
  },
  {
    id: 'market-table',
    title: 'The Saturday Market Table',
    category: 'Chef’s table',
    host: 'Atelier Dining',
    dateLabel: 'Sun, Oct 18',
    timeLabel: '12:30 PM',
    venue: 'Atelier Dining Room',
    neighborhood: 'Indiranagar, Bengaluru',
    duration: '2 hours',
    price: 1400,
    capacity: 12,
    summary: 'A relaxed lunch built around the morning market.',
    description: 'Join the kitchen at one long table for a generous, changing lunch. The menu follows what looks best at the market that morning.',
    sessions: ['12:30 PM', '1:00 PM'],
    includes: ['Four shared courses', 'Seasonal welcome drink', 'Small group seating'],
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=85',
  },
  {
    id: 'pasta-workshop',
    title: 'Handmade Pasta, Together',
    category: 'Workshop',
    host: 'Nonna’s Kitchen',
    dateLabel: 'Sat, Oct 24',
    timeLabel: '4:00 PM',
    venue: 'Nonna’s Kitchen Studio',
    neighborhood: 'Jubilee Hills, Hyderabad',
    duration: '2 hours',
    price: 1100,
    capacity: 10,
    summary: 'Learn the shape, feel, and rhythm of fresh pasta.',
    description: 'Make fresh pasta from scratch with a small group, then sit down together to enjoy the dish you made with a simple seasonal sauce.',
    sessions: ['4:00 PM', '6:30 PM'],
    includes: ['All ingredients and tools', 'Hands-on instruction', 'Shared meal and recipe card'],
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=85',
  },
  {
    id: 'tea-pairing',
    title: 'Tea & Small Plates',
    category: 'Tasting',
    host: 'Common Ground',
    dateLabel: 'Sun, Oct 25',
    timeLabel: '5:30 PM',
    venue: 'Common Ground Café',
    neighborhood: 'Fort, Mumbai',
    duration: '90 minutes',
    price: 850,
    capacity: 16,
    summary: 'A guided tasting of Indian teas with five small plates.',
    description: 'Explore fragrant single-origin teas alongside a menu of small plates. Learn how aroma, texture, and temperature bring each pairing to life.',
    sessions: ['5:30 PM', '7:00 PM'],
    includes: ['Five tea tastings', 'Five paired small plates', 'Guided tasting notes'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85',
  },
];

export const getDiningEvent = (eventId: string): DiningEvent | undefined =>
  DINING_EVENTS.find(event => event.id === eventId);

export const EVENT_CATEGORIES = ['All', ...new Set(DINING_EVENTS.map(event => event.category))];