import { StyleSheet } from 'react-native';
import { COLORS } from '@shared/constants/colors.constants';
import {
  EFonts,
  moderateScale,
  RADIUS,
  SPACING,
} from '@shared/constants/styles.constants';
import { ITheme } from '@shared/types/theme.types';

export const styling = (theme: ITheme) =>
  StyleSheet.create({
    screen: {
      flex: 1,
    },
    content: {
      flexGrow: 1,
      padding: SPACING.MD,
      paddingBottom: SPACING['2XL'],
    },
    headerContent: { gap: SPACING.MD, marginBottom: SPACING.MD },
    topRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: SPACING.SM,
    },
    headingCopy: { flex: 1, gap: SPACING.XS },
    eyebrow: {
      color: COLORS[theme]['brand-primary'],
      fontFamily: EFonts.SEMI_BOLD,
    },
    title: { fontSize: 24 },
    cartButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: RADIUS.SM,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
      backgroundColor: COLORS[theme].surface,
    },
    cartBadge: {
      position: 'absolute',
      right: -4,
      top: -5,
      minWidth: 19,
      height: 19,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: RADIUS.FULL,
      backgroundColor: COLORS[theme]['brand-primary'],
    },
    badgeText: { color: '#FFFFFF', fontSize: 10 },
    searchEntry: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.SM,
      paddingHorizontal: SPACING.MD,
      borderRadius: RADIUS.SM,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
      backgroundColor: COLORS[theme].surface,
    },
    searchPlaceholder: { flex: 1, color: COLORS[theme]['text-muted'] },
    featured: { overflow: 'hidden', borderRadius: RADIUS.MD },
    hero: {
      height: moderateScale(210),
      justifyContent: 'flex-end',
      overflow: 'hidden',
      padding: SPACING.MD,
    },
    heroImage: { borderRadius: RADIUS.MD },
    heroShade: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(13, 27, 20, 0.45)',
    },
    heroContent: { gap: SPACING.SM },
    featuredEyebrow: { color: 'rgba(255,255,255,0.86)', fontFamily: EFonts.SEMI_BOLD },
    heroTitle: { color: '#FFFFFF', maxWidth: 280 },
    heroMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    heroMetaText: { color: '#FFFFFF' },
    sectionHeading: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: SPACING.SM,
    },
    sectionCopy: { gap: SPACING.XS },
    secondary: { color: COLORS[theme]['text-secondary'] },
    tagSkeletonRow: {
      flexDirection: 'row',
      gap: SPACING.XS,
      paddingHorizontal: SPACING.MD,
      paddingVertical: SPACING.XS,
    },
    recipeSkeletonContainer: {
      gap: SPACING.SM,
    },
    tagList: { gap: SPACING.XS, paddingRight: SPACING.MD },
    tagChip: {
      minHeight: moderateScale(34),
      justifyContent: 'center',
      paddingHorizontal: SPACING.MD,
      borderRadius: RADIUS.FULL,
      borderWidth: 1,
      borderColor: COLORS[theme].border,
      backgroundColor: COLORS[theme].surface,
    },
    tagLabel: { color: COLORS[theme]['text-secondary'] },
    listHeading: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: SPACING.SM,
    },
    ordersLink: { paddingVertical: SPACING.XS, paddingLeft: SPACING.SM },
    ordersLabel: { color: COLORS[theme]['brand-primary'] },
    sortControls: { flexDirection: 'row', gap: SPACING.XS },
    stateContainer: { minHeight: moderateScale(180), alignItems: 'center', justifyContent: 'center', gap: SPACING.SM },
    retryButton: {
      minHeight: 40,
      justifyContent: 'center',
      marginTop: SPACING.XS,
      paddingHorizontal: SPACING.LG,
      borderRadius: RADIUS.SM,
      backgroundColor: COLORS[theme]['brand-primary'],
    },
    retryLabel: { color: '#FFFFFF' },
    footerLoader: { padding: SPACING.MD },
  });
