import { ITheme } from "@shared/types/theme.types";
import { StyleSheet } from "react-native";

export const styling = (_theme: ITheme) => StyleSheet.create({
    screen: { flex: 1 },
    header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
    backBtn: { paddingBottom: 6 },
    searchContainer: { paddingHorizontal: 20, paddingVertical: 10 },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 14,
        minHeight: 48,
    },
    input: { flex: 1, fontSize: 15 },
    currentLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    currentLocationText: { flex: 1, gap: 2 },
    currentLocationTitle: { fontWeight: '700' },
    savedSection: { paddingHorizontal: 20, paddingTop: 16 },
    sectionTitle: { marginBottom: 12 },
    savedItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        marginBottom: 10,
    },
    savedLabel: { fontWeight: '700' },
    iconCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addressTextWrapper: { flex: 1, gap: 2 },
    predictionsList: { paddingHorizontal: 20 },
    predictionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 14,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    predictionText: { flex: 1, gap: 3 },
    predictionPrimary: { fontWeight: '600' },
});